---

- name: Install Kibana
  ansible.builtin.apt:
    name: kibana
    state: present

- name: Configure Kibana
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: restart kibana

- name: Enable and start Kibana service
  ansible.builtin.systemd:
    name: kibana
    enabled: true
    state: started