---
- name: restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: restart metricbeat
  ansible.builtin.systemd:
    name: metricbeat
    state: restarted
    enabled: yes