---

- name: Install ES
  ansible.builtin.apt:
    name: elasticsearch
    state: present

- name: Configure ES
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Enable and start ES service
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    state: started
