---
- name: Install Logstash
  ansible.builtin.apt:
    name: logstash
    state: present

- name: Configure Logstash
  ansible.builtin.template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
  notify: restart logstash

- name: Enable and start Logstash service
  ansible.builtin.systemd:
    name: logstash
    enabled: true
    state: started