---
- name: Install net-tools
  ansible.builtin.apt:
    name: net-tools
    state: present

- name: Import public GPG key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add ES repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
- name: Install Filebeat
  ansible.builtin.apt:
    name: filebeat
    state: present

- name: Configure Filebeat
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat

- name: Install metricbeat
  ansible.builtin.apt:
    name: metricbeat
    state: present

- name: Configure metricbeat
  ansible.builtin.template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
  notify: restart metricbeat


- name: Load the index template to ES and dashboard to Kibana
  shell: |
    filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["3.138.105.41:9200"]'
    filebeat setup -E output.logstash.enabled=false -E output.elasticsearch.hosts=['3.138.105.41:9200'] -E setup.kibana.host=3.138.105.41:5601

- name: Load the dashboard to ELK
  shell: |
    metricbeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["3.138.105.41:9200"]'
    metricbeat setup -E output.logstash.enabled=false -E output.elasticsearch.hosts=['3.138.105.41:9200'] -E setup.kibana.host=3.138.105.41:5601